[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# CORS headers for ALL functions (adds on top of what we send in code)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"              # you can lock to https://scopeonride.webflow.io after it works
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Admin-Email"
    Access-Control-Max-Age = "86400"
